#!/bin/bash

echo "🧪 Testing Image Reveal Animation..."
echo "===================================="
echo ""
echo "The animation should work as follows:"
echo "1. 'Getting started...' (1 second)"
echo "2. 'Creating image. May take a moment...' (until image loads)"
echo "3. 'Image ready! Revealing...' (2 seconds with sliding overlay)"
echo "4. 'Image created.' (fully revealed)"
echo ""
echo "🔍 Check browser console for these logs:"
echo "- [ImageGeneration] Image state: { hasImage: true, loadingState: 'generating' }"
echo "- [ImageGeneration] Starting reveal animation"
echo "- [ImageGeneration] Animation progress: { elapsed: X, progress: Y, newY: Z }"
echo "- [ImageGeneration] Reveal animation completed"
echo "- [ImageGeneration] Calling onComplete"
echo ""
echo "📝 Common issues to check:"
echo "1. Is the image URL actually being set? (hasImage prop)"
echo "2. Are there any JavaScript errors in the console?"
echo "3. Is the overlay CSS being applied? (Check DevTools)"
echo ""
echo "🛠️ Debug steps:"
echo "1. Open DevTools (F12)"
echo "2. Go to Console tab"
echo "3. Generate a new image"
echo "4. Watch for the logs above"
echo "5. Check Elements tab for .image-generation-overlay"
echo "   - Should have data-y attribute changing from 0 to 100"
echo "   - Should have transform: translateY(X%) style"
echo ""
echo "✅ Server is running on port 3006"
echo "Visit: http://localhost:3006"
