#!/bin/bash

echo "Debugging Sequential Thinking Tool Display"
echo "=========================================="
echo ""
echo "This script will help debug why sequential thinking results aren't showing"
echo ""
echo "Steps to debug:"
echo "1. Start the dev server: npm run dev"
echo "2. Open browser console (F12)"
echo "3. Send a message like: 'Think step by step about how to build an MCP server'"
echo ""
echo "What to look for in the console:"
echo "- [DEBUG] Full AI response: Should show the [TOOL_CALL] block"
echo "- [MCPToolsContext] Parsing tool call: Should show the tool being parsed"
echo "- [parseToolCallsFromContent] Found TOOL_CALL block: Should show the content"
echo "- [parseToolCallsFromContent] Successfully parsed tool call: Should show success"
echo ""
echo "What to check in the Network tab:"
echo "- Look for the /api/chat request"
echo "- Check the Response tab to see the streaming data"
echo "- Each line should be in format: 0:\"escaped content\""
echo ""
echo "Common issues:"
echo "1. Tool call not being sent properly from backend"
echo "2. Tool call not being parsed correctly in frontend"
echo "3. Tool results not being displayed in UI"
echo ""
echo "To test the fix manually:"
echo "1. Verify the tool executes (check terminal logs)"
echo "2. Verify the tool result is sent (check Network tab)"
echo "3. Verify the tool is parsed (check console logs)"
echo "4. Verify the UI updates (check the chat interface)"