#!/bin/bash

echo "Transcription Timestamps Tab Test"
echo "================================="
echo ""
echo "This script helps test the restored timestamps tab feature"
echo ""
echo "Steps to test:"
echo "1. Start the dev server: npm run dev"
echo "2. Open the app in your browser"
echo "3. Upload an audio or video file (MP3, MP4, etc.)"
echo "4. Wait for transcription to complete"
echo ""
echo "Expected behavior:"
echo "✓ File uploads successfully"
echo "✓ Transcription completes (may take a moment)"
echo "✓ 'Timestamps' tab appears in Canvas view (right panel)"
echo "✓ Tab shows Clock icon"
echo "✓ Clicking tab shows timestamped segments"
echo "✓ Each segment shows:"
echo "  - Blue timestamp (start time)"
echo "  - Transcribed text"
echo "  - Duration in gray"
echo "✓ Removing file clears timestamps tab"
echo ""
echo "Troubleshooting:"
echo "- If no Timestamps tab: Check if transcription has segments"
echo "- If transcription fails: Check OPENAI_API_KEY in .env.local"
echo "- Open browser console (F12) to see transcription data"
echo ""
echo "Look for console logs:"
echo "- 'Transcription successful:' with segments array"
echo "- Check segments have start, end, and text properties"